/**
 * Anthropic's own words for the Group D probes: what a replayed thinking block,
 * the default thinking display, prompt caching and structured outputs must do
 * on a genuine backend.
 *
 * Retrieved from https://platform.claude.com/docs/ with `.md` appended. Link
 * markup is reduced to its text; code spans and emphasis are kept as written.
 */

import { citation } from './citation.js'

const RETRIEVED = '2026-09-24'

const ERRORS = 'https://platform.claude.com/docs/en/api/errors'
const MESSAGES = 'https://platform.claude.com/docs/en/api/messages/create'
const CONTEXT_WINDOWS = 'https://platform.claude.com/docs/en/build-with-claude/context-windows'
const OPUS_55_MIGRATION = 'https://platform.claude.com/docs/en/models/opus-5-5/migration-guide'
const SONNET_5_MIGRATION = 'https://platform.claude.com/docs/en/models/sonnet-5/migration-guide'
const FABLE_51 = 'https://platform.claude.com/docs/en/models/fable-5-1/whats-new-fable-5-1'
const CACHING = 'https://platform.claude.com/docs/en/build-with-claude/prompt-caching'
const STRUCTURED = 'https://platform.claude.com/docs/en/build-with-claude/structured-outputs'

export const ANTHROPIC_THINKING_MODIFIED_400 = citation(
  ERRORS,
  'If the most recent assistant message contains `thinking` or `redacted_thinking` blocks that were edited, reordered, filtered out, or reconstructed before being sent back to the API, the request returns a 400 `invalid_request_error`.',
  RETRIEVED,
)

export const ANTHROPIC_THINKING_CANNOT_BE_MODIFIED = citation(
  ERRORS,
  '`thinking` or `redacted_thinking` blocks in the latest assistant message cannot be modified. These blocks must remain as they were in the original response.',
  RETRIEVED,
)

export const ANTHROPIC_THINKING_PREFIX_BOUND = citation(
  ERRORS,
  'On Claude Fable 5.1 and Claude Opus 5.5, the API accepts a replayed thinking block only while the `system` prompt, `tools`, and messages that preceded it are unchanged.',
  RETRIEVED,
)

export const ANTHROPIC_THINKING_UNREADABLE_DROPPED = citation(
  ERRORS,
  "A block from a model the target model can't read is dropped rather than rejected.",
  RETRIEVED,
)

export const ANTHROPIC_THINKING_SIGNATURE = citation(
  MESSAGES,
  'The `signature` value of this thinking block, exactly as returned by the API in a previous response. Used to verify that the block was generated by Claude.',
  RETRIEVED,
)

export const ANTHROPIC_THINKING_SIGNATURES_VERIFIED = citation(
  CONTEXT_WINDOWS,
  'The API uses cryptographic signatures to verify thinking block authenticity. If you modify a thinking block, the API returns an error.',
  RETRIEVED,
)

export const ANTHROPIC_THINKING_KEPT = citation(
  CONTEXT_WINDOWS,
  'On Claude Opus 4.5 and later Opus models, Claude Sonnet 4.6 and later Sonnet models, Claude Fable 5.1, Claude Mythos 5.1, Claude Fable 5, Claude Mythos 5, and Claude Mythos Preview, the API keeps previous thinking blocks by default, and they count toward the context window like any other input tokens.',
  RETRIEVED,
)

export const ANTHROPIC_THINKING_STRIPPED = citation(
  CONTEXT_WINDOWS,
  'On earlier Opus and Sonnet models and all Haiku models, the API automatically strips previous thinking blocks from the conversation history when you pass them back, which preserves token capacity for conversation content.',
  RETRIEVED,
)

export const ANTHROPIC_DISPLAY_OMITTED_OPUS_55 = citation(
  OPUS_55_MIGRATION,
  '`thinking.display` defaults to `"omitted"`, so `thinking` blocks arrive with an empty `thinking` field alongside their `signature`.',
  RETRIEVED,
)

export const ANTHROPIC_DISPLAY_OMITTED_FROM_OPUS_47 = citation(
  OPUS_55_MIGRATION,
  'Thinking blocks still appear in the response stream on Claude Opus 4.7 and later models, but their `thinking` field is empty unless you explicitly opt in. This is a silent change from Claude Opus 4.6, where the default was to return summarized thinking text.',
  RETRIEVED,
)

export const ANTHROPIC_DISPLAY_OMITTED_SONNET_5 = citation(
  SONNET_5_MIGRATION,
  '`thinking.display` defaults to `"omitted"` on Claude Sonnet 5 (it defaulted to `"summarized"` on Claude Sonnet 4.6), so thinking blocks arrive with an empty `thinking` field',
  RETRIEVED,
)

export const ANTHROPIC_DISPLAY_OMITTED_FABLE_51 = citation(
  FABLE_51,
  '`thinking.display` defaults to `"omitted"`. `"summarized"` is available, and the raw chain of thought is never returned.',
  RETRIEVED,
)

export const ANTHROPIC_CACHE_BELOW_MINIMUM = citation(
  CACHING,
  'Shorter prompts cannot be cached, even if marked with `cache_control`. Any requests to cache fewer than this number of tokens will be processed without caching, and no error is returned.',
  RETRIEVED,
)

export const ANTHROPIC_CACHE_NOT_CACHED = citation(
  CACHING,
  'if both `cache_creation_input_tokens` and `cache_read_input_tokens` are 0, the prompt was not cached (likely because it did not meet the minimum length requirement).',
  RETRIEVED,
)

export const ANTHROPIC_CACHE_EVERY_PLATFORM = citation(
  CACHING,
  'These minimums apply on every platform where each model is available.',
  RETRIEVED,
)

export const ANTHROPIC_CACHE_IDENTICAL_PREFIX = citation(
  CACHING,
  'Cache hits require 100% identical prompt segments, including all text and images up to and including the block marked with cache control.',
  RETRIEVED,
)

export const ANTHROPIC_CACHE_WRITE_PRICE = citation(
  CACHING,
  '5-minute cache write tokens are 1.25 times the base input tokens price',
  RETRIEVED,
)

export const ANTHROPIC_STRUCTURED_JSON_OUTPUTS = citation(
  STRUCTURED,
  "**JSON outputs** (`output_config.format`): Get Claude's response in a specific JSON format",
  RETRIEVED,
)

export const ANTHROPIC_STRUCTURED_CONSTRAINED = citation(
  STRUCTURED,
  'Structured outputs guarantee schema-compliant responses through constrained decoding:',
  RETRIEVED,
)

export const ANTHROPIC_STRUCTURED_EXCEPTIONS = citation(
  STRUCTURED,
  'While structured outputs guarantee schema compliance in most cases, there are scenarios where the output may not match your schema:',
  RETRIEVED,
)

export const ANTHROPIC_STRUCTURED_CAPITALIZATION = citation(
  STRUCTURED,
  "Structured outputs don't guarantee the capitalization of string `enum` and `const` values: Claude may return a value that differs from your schema only in capitalization, typically in the first letter of a word following a space.",
  RETRIEVED,
)
