/**
 * OpenAI's own words for the Group D probes: structured outputs, `logit_bias`
 * and `logprobs` on a genuine backend. `OPENAI_LOGIT_BIAS` in `openai.ts` is
 * the first half of the `logit_bias` description; these are the rest.
 *
 * Retrieved from https://developers.openai.com/ with `.md` appended. Link
 * markup is reduced to its text.
 */

import { citation } from './citation.js'

const RETRIEVED = '2026-09-24'

const CHAT = 'https://developers.openai.com/api/reference/resources/chat'
const STRUCTURED = 'https://developers.openai.com/api/docs/guides/structured-outputs'

export const OPENAI_STRUCTURED_ADHERES = citation(
  STRUCTURED,
  "Structured Outputs is a feature that ensures the model will always generate responses that adhere to your supplied JSON Schema, so you don't need to worry about the model omitting a required key, or hallucinating an invalid enum value.",
  RETRIEVED,
)

export const OPENAI_STRUCTURED_ADDITIONAL_PROPERTIES = citation(
  STRUCTURED,
  'Structured Outputs only supports generating specified keys / values, so we require developers to set `additionalProperties: false` to opt into Structured Outputs.',
  RETRIEVED,
)

export const OPENAI_STRUCTURED_EXCEPTIONS = citation(
  STRUCTURED,
  'This can happen in the case of a refusal, if the model refuses to answer for safety reasons, or if for example you reach a max tokens limit and the response is incomplete.',
  RETRIEVED,
)

export const OPENAI_STRUCTURED_MODELS = citation(
  STRUCTURED,
  'However, Structured Outputs with `response_format: {type: "json_schema", ...}` is only supported with the `gpt-4o-mini`, `gpt-4o-mini-2024-07-18`, and `gpt-4o-2024-08-06` model snapshots and later.',
  RETRIEVED,
)

export const OPENAI_STRUCTURED_STRICT = citation(
  CHAT,
  'Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the `schema` field.',
  RETRIEVED,
)

export const OPENAI_LOGIT_BIAS_ADDED = citation(
  CHAT,
  'Mathematically, the bias is added to the logits generated by the model prior to sampling.',
  RETRIEVED,
)

export const OPENAI_LOGIT_BIAS_EXCLUSIVE = citation(
  CHAT,
  'values like -100 or 100 should result in a ban or exclusive selection of the relevant token.',
  RETRIEVED,
)

export const OPENAI_LOGPROBS = citation(
  CHAT,
  'Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the `content` of `message`.',
  RETRIEVED,
)

export const OPENAI_LOGPROBS_BYTES = citation(
  CHAT,
  'A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.',
  RETRIEVED,
)

export const OPENAI_LOGPROB_VALUE = citation(
  CHAT,
  'The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.',
  RETRIEVED,
)
