/**
 * OpenAI's words on what a Chat Completions or Responses answer reports about
 * itself: the output ceiling, the length stop, `usage` and its breakdowns, the
 * response's `model` and `id`. Group B's accounting probes check a response
 * against these.
 */

import { citation } from './citation.js'

const CHAT = 'https://developers.openai.com/api/reference/resources/chat'
const RESPONSES = 'https://developers.openai.com/api/reference/resources/responses/methods/create'
const REASONING = 'https://developers.openai.com/api/docs/guides/reasoning'
const RETRIEVED = '2026-09-24'

export const OPENAI_CHAT_MAX_COMPLETION_TOKENS = citation(
  CHAT,
  'An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and',
  RETRIEVED,
)

export const OPENAI_CHAT_LENGTH_FINISH = citation(
  CHAT,
  '`length` if the maximum number of tokens specified in the request was reached,',
  RETRIEVED,
)

export const OPENAI_CHAT_COMPLETION_TOKENS = citation(
  CHAT,
  'Number of tokens in the generated completion.',
  RETRIEVED,
)

export const OPENAI_CHAT_COMPLETION_BREAKDOWN = citation(
  CHAT,
  'Breakdown of tokens used in a completion.',
  RETRIEVED,
)

export const OPENAI_CHAT_REASONING_TOKENS = citation(
  CHAT,
  'Tokens generated by the model for reasoning.',
  RETRIEVED,
)

export const OPENAI_CHAT_PROMPT_BREAKDOWN = citation(
  CHAT,
  'Breakdown of tokens used in the prompt.',
  RETRIEVED,
)

export const OPENAI_CHAT_CACHED_TOKENS = citation(
  CHAT,
  'Cached tokens present in the prompt.',
  RETRIEVED,
)

export const OPENAI_CHAT_RESPONSE_MODEL = citation(
  CHAT,
  'The model used for the chat completion.',
  RETRIEVED,
)

export const OPENAI_CHAT_ID_EXAMPLE = citation(
  CHAT,
  '"id": "chatcmpl-B9MBs8CjcvOU2jLn4n570S5qMJKcT",',
  RETRIEVED,
)

export const OPENAI_RESPONSES_MAX_OUTPUT_TOKENS = citation(
  RESPONSES,
  'An upper bound for the number of tokens that can be generated for a response, including visible output tokens and',
  RETRIEVED,
)

export const OPENAI_RESPONSES_INCOMPLETE = citation(
  REASONING,
  "If the generated tokens reach the context window limit or the `max_output_tokens` value you've set, you'll receive a response with a `status` of `incomplete` and `incomplete_details` with `reason` set to `max_output_tokens`.",
  RETRIEVED,
)

export const OPENAI_RESPONSES_TOTAL_TOKENS = citation(
  RESPONSES,
  'The total number of tokens used.',
  RETRIEVED,
)

export const OPENAI_RESPONSES_INPUT_BREAKDOWN = citation(
  RESPONSES,
  'A detailed breakdown of the input tokens.',
  RETRIEVED,
)

export const OPENAI_RESPONSES_CACHED_TOKENS = citation(
  RESPONSES,
  'The number of tokens that were retrieved from the cache.',
  RETRIEVED,
)

export const OPENAI_RESPONSES_OUTPUT_BREAKDOWN = citation(
  RESPONSES,
  'A detailed breakdown of the output tokens.',
  RETRIEVED,
)

export const OPENAI_RESPONSES_INPUT_TOKENS = citation(
  RESPONSES,
  'The number of input tokens.',
  RETRIEVED,
)

export const OPENAI_RESPONSES_MODEL = citation(
  RESPONSES,
  'Model ID used to generate the response, like `gpt-6-astra`.',
  RETRIEVED,
)

export const OPENAI_RESPONSES_ID_EXAMPLE = citation(
  RESPONSES,
  '"id": "resp_686eef60237881a2bd1180bb8b13de430e34c516d176ff86",',
  RETRIEVED,
)

export const OPENAI_CHAT_USAGE = citation(
  CHAT,
  'Usage statistics for the completion request.',
  RETRIEVED,
)
